/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentureStudioRouteImport } from './routes/venture-studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdvisoryBoardRouteImport } from './routes/advisory-board'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorsSlugRouteImport } from './routes/advisors.$slug'

const VentureStudioRoute = VentureStudioRouteImport.update({
  id: '/venture-studio',
  path: '/venture-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisoryBoardRoute = AdvisoryBoardRouteImport.update({
  id: '/advisory-board',
  path: '/advisory-board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsSlugRoute = AdvisorsSlugRouteImport.update({
  id: '/advisors/$slug',
  path: '/advisors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venture-studio': typeof VentureStudioRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venture-studio': typeof VentureStudioRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisory-board': typeof AdvisoryBoardRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/refund': typeof RefundRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/venture-studio': typeof VentureStudioRoute
  '/advisors/$slug': typeof AdvisorsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisory-board'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/venture-studio'
    | '/advisors/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisory-board'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/venture-studio'
    | '/advisors/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advisory-board'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/refund'
    | '/sitemap.xml'
    | '/terms'
    | '/venture-studio'
    | '/advisors/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvisoryBoardRoute: typeof AdvisoryBoardRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRoute
  RefundRoute: typeof RefundRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VentureStudioRoute: typeof VentureStudioRoute
  AdvisorsSlugRoute: typeof AdvisorsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venture-studio': {
      id: '/venture-studio'
      path: '/venture-studio'
      fullPath: '/venture-studio'
      preLoaderRoute: typeof VentureStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisory-board': {
      id: '/advisory-board'
      path: '/advisory-board'
      fullPath: '/advisory-board'
      preLoaderRoute: typeof AdvisoryBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors/$slug': {
      id: '/advisors/$slug'
      path: '/advisors/$slug'
      fullPath: '/advisors/$slug'
      preLoaderRoute: typeof AdvisorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvisoryBoardRoute: AdvisoryBoardRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRoute,
  RefundRoute: RefundRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VentureStudioRoute: VentureStudioRoute,
  AdvisorsSlugRoute: AdvisorsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
