/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStartupsRouteImport } from './routes/_app/startups'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCollegesRouteImport } from './routes/_app/colleges'
import { Route as AppBroadcastsRouteImport } from './routes/_app/broadcasts'
import { Route as AppApprovalsRouteImport } from './routes/_app/approvals'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStartupsRoute = AppStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCollegesRoute = AppCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastsRoute = AppBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/colleges': typeof AppCollegesRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/startups': typeof AppStartupsRoute
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/approvals': typeof AppApprovalsRoute
  '/broadcasts': typeof AppBroadcastsRoute
  '/colleges': typeof AppCollegesRoute
  '/dashboard': typeof AppDashboardRoute
  '/events': typeof AppEventsRoute
  '/startups': typeof AppStartupsRoute
  '/tasks': typeof AppTasksRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/broadcasts': typeof AppBroadcastsRoute
  '/_app/colleges': typeof AppCollegesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/events': typeof AppEventsRoute
  '/_app/startups': typeof AppStartupsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/team': typeof AppTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approvals'
    | '/broadcasts'
    | '/colleges'
    | '/dashboard'
    | '/events'
    | '/startups'
    | '/tasks'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/approvals'
    | '/broadcasts'
    | '/colleges'
    | '/dashboard'
    | '/events'
    | '/startups'
    | '/tasks'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/analytics'
    | '/_app/approvals'
    | '/_app/broadcasts'
    | '/_app/colleges'
    | '/_app/dashboard'
    | '/_app/events'
    | '/_app/startups'
    | '/_app/tasks'
    | '/_app/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/startups': {
      id: '/_app/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof AppStartupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colleges': {
      id: '/_app/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AppCollegesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcasts': {
      id: '/_app/broadcasts'
      path: '/broadcasts'
      fullPath: '/broadcasts'
      preLoaderRoute: typeof AppBroadcastsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppBroadcastsRoute: typeof AppBroadcastsRoute
  AppCollegesRoute: typeof AppCollegesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventsRoute: typeof AppEventsRoute
  AppStartupsRoute: typeof AppStartupsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTeamRoute: typeof AppTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppBroadcastsRoute: AppBroadcastsRoute,
  AppCollegesRoute: AppCollegesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEventsRoute: AppEventsRoute,
  AppStartupsRoute: AppStartupsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTeamRoute: AppTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
